### ISSUE TITLE
Índice da apresentação atual 

### ISSUE THREAD

**Issue by daliangowert** [holyrics/API-Server#1]
Olá, olhei toda a documentação em busca de uma requisição que retornasse o índice da apresentação atual e não encontrei (A requisição GetCurrentPresentation retorna apenas id e nome da apresentação).

Por exemplo, em uma letra de música com 3 slides, precisava saber qual o índice do slide que estava sendo apresentado no momento(se era o 0, 1 ou 2). Também seria interessante saber a quantidade de slides que essa letra possuía, para quando terminar a música (chegando a slide 2) eu poder acionar o gatilho da aplicação que estou implementando.

Será que existe alguma forma de fazer isso?

**Comment by holyrics** [comment]
No momento o método `GetCurrentPresentation` não retorna informações detalhadas.
Nas próximas atualizações posso verificar essa possibilidade.

Alternativamente você pode contornar essa necessidade de outra forma:
- Crie um gatilho no Holyrics (ao exibir - qualquer item - slide música) e selecione o receptor **Holyrics - Script**;
- No javascript do gatilho, salve as informações do slide atual utilizando o método setGlobal, exemplo `h.setGlobal('slide_atual', obj)`;
- No menu arquivo, api server, javascript, implemente uma ação personalizada para as requisições API, onde você pode utilizar o valor 'slide_atual' salvo na memória para retornar na requisição, exemplo `h.getGlobal('slide_atual')`.

Com a implementação personalizada acima você pode, na prática, criar suas próprias ações para retornar o conteúdo conforme desejar.
No caso, você vai utilizar a ferramenta de gatilho para salvar as informações detalhadas do slide atual na memória compartilhada javascript, e na implementação personalizada da API você vai obter e retornar essa mesma informação como resposta da requisição http.

Obs.: Recomento criar também um gatilho "ao encerrar - qualquer música" para executar `h.setGlobal('slide_atual', null)`, dessa forma você sabe que se `h.getGlobal('slide_atual')` for igual a `null`, então não tem uma música em exibição.

**Comment by daliangowert** [comment]
Nossa, bacana demais! Não sabia que existia essa possibilidade de criar uma requisição API personalizada. 

Muito obrigado mesmo, ajudou bastante.

**Comment by holyrics** [comment]
Os parâmetros de retorno: `slide_number`, `total_slides` e `slide_type` foram adicionados no método [GetCurrentPresentation](https://github.com/holyrics/jslib#hlygetcurrentpresentation)
