### ISSUE TITLE
Erro de CORS ao realizar a requisição pelo Browser

### ISSUE THREAD

**Issue by Lucasmg37** [holyrics/API-Server#2]
Olá tudo bem?
Estou tentando implementar a busca de alguns dados na Holyics API, pelo browser, utilizando o axios como cliente http.
Segue implementação abaixo.

```
import axios from "axios";


export class ClientHolyrics {
  constructor(baseUrl, key) {
    this.key = key
    this.client = axios.create({
      baseURL: baseUrl + '/api/',
    })
  }

  async getSongsPlaylist() {
    try {
      const {data} = await this.client?.post('GetSongPlaylist', { params: { token: this.key }})
      return data
    } catch (error) {
      console.log(error)
    }
  }
}
```

Porém, estou recebendo um erro de bloqueio por políticas do CORS.
![image](https://github.com/holyrics/API-Server/assets/25160385/6fda2fc1-baa9-4335-b6c8-a2eeb8350036)

Realizei teste também com o _fetch_ porém sem sucesso.

```
var myHeaders = new Headers();
myHeaders.append("Content-Type", "application/json");

var requestOptions = {
  method: 'POST',
  headers: myHeaders,
  redirect: 'follow'
};

fetch("http://192.168.2.117:8091/api/GetSongPlaylist?token=MaXtn4fmH2AvMbUo", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));
```

Testes utilizando o [postman](https://www.postman.com/), são bem sucedidos, poertanto o recurso está habilitado corretamente no Holyrics.

Existe alguma maneira de se fazer requisições pelo browser para a API localmente?

Nosso popósito é realizar certas automatizações no holyrics, por meio de uma plataforma web, que está sendo implementada em nossa aplicação de gestão.

Desde já agradeço.
Abraços.

**Comment by holyrics** [comment]
Olá,

Verifiquei que a opção `Access-Control-Allow-Origin: *` está correta no header, mas por conta do `Content-Type: application/json` a opção `Access-Control-Allow-Headers: *` também precisa ser retornada no header, por isso o bloqueio ocorre atualmente.

Essa semana irei disponibilizar uma versão beta do programa no grupo beta no Telegram, que já terá essa correção.
Se quiser ter acesso para testar: https://holyrics.com.br/_beta/join.html

Obrigado!
