### ISSUE TITLE
Holyrics don't show token

### ISSUE THREAD

**Issue by tiagodevss** [holyrics/API-Server#4]
![image](https://github.com/holyrics/API-Server/assets/76692160/505e85c0-95db-4a21-b5a5-a45658451f33)

Hi, the holyrics isn't showing the token in this window, how can I use him?

**Comment by holyrics** [comment]
Olá, é necessário copiar o token clicando com o botão direito do mouse no item.

**Comment by tiagodevss** [comment]
Muito obrigado!!
